In [1]:
import numpy as np
import pandas as pd

In [2]:
#Es.1
mat = [[0, 1, 2, 3, 4], 
       [5, 6, 7, 8, 9], 
       [10, 11, 12, 13, 14]]

print(mat[0][0])
print(mat[1][3])
print(mat[2][4])
print(mat[1][0])

0
8
14
5


In [4]:
#Es.2
import math

print(math.sin(60))
print(math.cos(60))
print(math.factorial(10))

print(math.pi)

-0.3048106211022167
-0.9524129804151563
3628800
3.141592653589793


In [5]:
#Es.3
print(math.degrees(math.pi))
help(math.degrees)

180.0
Help on built-in function degrees in module math:

degrees(x, /)
    Convert angle x from radians to degrees.



In [20]:
#Es.4
lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350]
import numpy as np
lst = np.array(lst)

vendita_massima = np.max(lst)
vendita_minima = np.min(lst)
print(vendita_massima)
print(vendita_minima)

vendite_maggiori = lst > 4999
print(vendite_maggiori)
print(lst[vendite_maggiori])

print(vendite_maggiori.size)

vendite_minori = lst < 3000
print(lst[vendite_minori])
print(len(lst[vendite_minori]))

8150
1280
[False  True  True False False False False False  True  True  True  True]
[5500 7200 6410 8150 7100 5350]
12
[2000 1280 1900 2500]
4


In [ ]:
#Es.5
fatturati_dict = {1997: 12_000, 1998: 15_000, 1999: 
                  20_000, 2000: 23_000, 2001: 25_000, 2002: 
                  17_000, 2003: 14_000, 2004: 21_000}

fatturati_series = pd.Series([12_000, 15_000, 20_000, 23_000, 
                              25_000, 17_000, 14_000, 21_000], 
                             index=range(1997, 2005))

fatturati_dict[1997] 
fatturati_series[1997]

In [21]:
#Es.6
import numpy as np 
stipendi = np.array( [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000] )

for stipendio in stipendi:
    stipendio_raddoppiato = stipendio*2
    print (stipendio_raddoppiato)

print (stipendi*2)

200
400
600
800
1000
1200
1400
1600
1800
2000
[ 200  400  600  800 1000 1200 1400 1600 1800 2000]


In [27]:
#Es.7
dati = [10, 9, 7, 29, 41, 18, 3, 2, 14, 25, 36, 12]

dati = list(set(dati))

if len(dati) <= 3:
    print(dati)
dati = sorted(dati, reverse=True)
print(dati [:3])

[41, 36, 29]


In [37]:
#Es.8
import numpy as np

dati = [10, 9, 7, 29, 41, 18, 3, 2, 14, 25, 36, 12]
k = 30

dati = np.array(dati)

filtro = dati >= k
media = dati[filtro].mean()
media = round (media,2)
print (f"la media dei numeri >= {k} è {media}")

la media dei numeri >= 30 è 38.5


In [39]:
#Es.9
numeri = [5, 2, 3, 4]

for numero in numeri:
    print("*" * numero)

*****
**
***
****


In [57]:
#Es.10
lista_cf = ["ABCDEF95G01A123B", "GHIJKL91M02A321C", 
            "MNOPQR89S03A456D", "STUVWX95Z04A654E",
            "XYZABC01D05A789F", "DEFGHI95J06A987G"]

cf_95 = []
for cf in lista_cf:
    if "95" in cf:
        cf_95.append(cf)
print(cf_95)       

for cf in cf_95:
    print("nome", cf[:3], "cognome", cf[3:6])

['ABCDEF95G01A123B', 'STUVWX95Z04A654E', 'DEFGHI95J06A987G']
nome ABC cognome DEF
nome STU cognome VWX
nome DEF cognome GHI


In [58]:
#Es.11
studenti = ["Alex", "Bob", "Cindy", "Dan", "Emma", "Faith", "Grace", "Henry"]
corsi = ["Cybersecurity", "Data Analyst", "Backend", "Frontend", "Data Analyst", "Backend", "Frontend", "Cybersecurity"] 
edizioni = [1, 2, 3, 2, 2, 1, 3, 3]

for indice in range (len(studenti)):
    edizione = edizioni[indice]
    studente = studenti[indice]
    if edizione == 1:
        print(studente)

Alex
Faith


In [62]:
#Es.12
prezzi = ["100 €", "200 €", "500 €", "10 €", "50 €", "70 €"]

prezzi_corretti = []

for prezzo in prezzi:
    prezzo_corretto = prezzo.replace("€", "$")
    prezzi_corretti.append(prezzo_corretto)

print(prezzi_corretti)

['100 $', '200 $', '500 $', '10 $', '50 $', '70 $']


In [63]:
#Es.13
studenti = ["Alex", "Bob", "Cindy", "Dan", "Emma", "Faith", "Grace", "Henry", "Isabelle", "John"]

squadra_1 = studenti[::2]
squadra_2 = studenti[1::2]

print (squadra_1)
print (squadra_2)

['Alex', 'Cindy', 'Emma', 'Grace', 'Isabelle']
['Bob', 'Dan', 'Faith', 'Henry', 'John']


In [70]:
#Es.14
guadagni = [100, 90, 70, 40, 50, 80, 90, 120, 80, 20, 50, 50]

precedenti = []
contatore = 1

for guadagno in guadagni:
    if len(precedenti) == 0:
        print(f"mese {contatore}: {guadagno} €")
    else:
        media_mesi_precedenti = np.mean(precedenti)
        print(f"mese {contatore}: {guadagno} € - la media dei mesi predenti è {media_mesi_precedenti}")
        if guadagno < media_mesi_precedenti:
            print(f"    il guadagno è minore")
        else:
            print(f"    il guadagno è maggiore")
    precedenti.append(guadagno)
    contatore += 1

mese 1: 100 €
mese 2: 90 € - la media dei mesi predenti è 100.0
    il guadagno è minore
mese 3: 70 € - la media dei mesi predenti è 95.0
    il guadagno è minore
mese 4: 40 € - la media dei mesi predenti è 86.66666666666667
    il guadagno è minore
mese 5: 50 € - la media dei mesi predenti è 75.0
    il guadagno è minore
mese 6: 80 € - la media dei mesi predenti è 70.0
    il guadagno è maggiore
mese 7: 90 € - la media dei mesi predenti è 71.66666666666667
    il guadagno è maggiore
mese 8: 120 € - la media dei mesi predenti è 74.28571428571429
    il guadagno è maggiore
mese 9: 80 € - la media dei mesi predenti è 80.0
    il guadagno è maggiore
mese 10: 20 € - la media dei mesi predenti è 80.0
    il guadagno è minore
mese 11: 50 € - la media dei mesi predenti è 74.0
    il guadagno è minore
mese 12: 50 € - la media dei mesi predenti è 71.81818181818181
    il guadagno è minore
